export default function ChiSiamo() {
  return (
    <>
      <section id="about-hero">
        <h1>About Hero</h1>
        <p>Content for about-hero will be generated by tasks</p>
      </section>
      <section id="story">
        <h2>Story</h2>
        <p>Content for story will be generated by tasks</p>
      </section>
      <section id="philosophy">
        <h2>Philosophy</h2>
        <p>Content for philosophy will be generated by tasks</p>
      </section>
    </>
  )
}
