export default function Contatti() {
  return (
    <>
      <section id="contact-hero">
        <h1>Contact Hero</h1>
        <p>Content for contact-hero will be generated by tasks</p>
      </section>
      <section id="contact-details">
        <h2>Contact Details</h2>
        <p>Content for contact-details will be generated by tasks</p>
      </section>
      <section id="opening-hours">
        <h2>Opening Hours</h2>
        <p>Content for opening-hours will be generated by tasks</p>
      </section>
    </>
  )
}
