export default function Gallery() {
  return (
    <>
      <section id="gallery-hero">
        <h1>Gallery Hero</h1>
        <p>Content for gallery-hero will be generated by tasks</p>
      </section>
      <section id="gallery-grid">
        <h2>Gallery Grid</h2>
        <p>Content for gallery-grid will be generated by tasks</p>
      </section>
    </>
  )
}
