export default function Home() {
  return (
    <>
      <section id="hero">
        <h1>Hero</h1>
        <p>Content for hero will be generated by tasks</p>
      </section>
      <section id="signature-preview">
        <h2>Signature Preview</h2>
        <p>Content for signature-preview will be generated by tasks</p>
      </section>
      <section id="brand-story-preview">
        <h2>Brand Story Preview</h2>
        <p>Content for brand-story-preview will be generated by tasks</p>
      </section>
    </>
  )
}
