export default function Menu() {
  return (
    <>
      <section id="menu-hero">
        <h1>Menu Hero</h1>
        <p>Content for menu-hero will be generated by tasks</p>
      </section>
      <section id="menu-categories">
        <h2>Menu Categories</h2>
        <p>Content for menu-categories will be generated by tasks</p>
      </section>
    </>
  )
}
