export default function Servizi() {
  return (
    <>
      <section id="services-hero">
        <h1>Services Hero</h1>
        <p>Content for services-hero will be generated by tasks</p>
      </section>
      <section id="services-overview">
        <h2>Services Overview</h2>
        <p>Content for services-overview will be generated by tasks</p>
      </section>
    </>
  )
}
